# List

# List is mutable?
List is mutable . we can add, remove, modifiy and replace the elements of a list.

In [1]:
ls=[34,56,[-2,45,56]]
ls[2][0] = "hi"
ls

[34, 56, ['hi', 45, 56]]

In [2]:
t = ["a","b","c","d","e"]

del t[1:3]
t[1] = 10
print(t)

['a', 10, 'e']


In [3]:
#(a)concatination of list
ls1=[23,56,89,4]
ls2=["hi",4.5,12]
ls3 = ls1+ ls2

In [4]:
ls3

[23, 56, 89, 4, 'hi', 4.5, 12]

In [5]:
#(b)Repetitation of list
ls=[1,2,3]
#Repeat this list for 3 times.
ls*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
ls = [1,2,3] # append a value in a list
ls.append(4)

In [7]:
ls

[1, 2, 3, 4]

In [8]:
#(d) difference between append and extend



### Solve above question with help of example

In [9]:
ls=[45,6,2,23,-3,0]
#i.sort list in ascending and descending
ls.sort()
print(ls)

[-3, 0, 2, 6, 23, 45]


In [10]:
ls.sort(reverse= True)
print(ls)

[45, 23, 6, 2, 0, -3]


In [11]:
#iii. delete elt from list based on list index eg: index=2
ls=[45,6,2,23,-3,0]
ls.pop(2)
print(ls)

[45, 6, 23, -3, 0]


In [12]:
#iv.delete a required elt by its value Eg: element=6
ls=[45,6,2,23,-3,0]
ls.remove(6)
print(ls)

[45, 2, 23, -3, 0]


In [13]:
#v. delete more than 1 element using del 
ls=[23,35,-4,65,12,3.5,"hi",45]
del ls[1:3]
print(ls)

[23, 65, 12, 3.5, 'hi', 45]


In [14]:
#vi. clear all elt from list
ls=[23,35,-4,65,12,3.5,"hi",45]
ls.clear()
print(ls)

[]


In [15]:
#vii.count the occurance of a elt in list
ls=[1,2,4,2,34,45,2,12,6]

In [16]:
#viii."hello how are you?" convert this string into list
string = "hello how are you?"
lst = string.split()
print(lst)

['hello', 'how', 'are', 'you?']


In [17]:
#ix.splitting a date into dd,mm,yyyy
d='06/02/2019'




### Use split finction to solve the above question

In [18]:
#Converting list into string
ls=["hello","how", "are","you"]
string = " ".join(ls)
print(string)

hello how are you


In [19]:
#2. Find average and std dev. of n integers.Procedure:

n= int(input())
ls = []
for i in range(n+1):
    ls.append(i)
print(ls)

20
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [20]:
#average
avg = sum(ls)/len(ls)
print(avg)

10.0


In [21]:
#Statistics
import statistics
std_dev = statistics.stdev(ls)
print(std_dev)

6.2048368229954285


In [22]:
#(b) write a program to check if the list is in asc order
ls_copy = ls[:]
ls_copy.sort()

if (ls == ls_copy):
    print("List is in ascending order")
else:
    print("List is not in ascending order")

List is in ascending order


### Resolve 

# SET

# What is a set? Differnce between set and list?
Set is used to store the multiple element in a single variable. It is one of the inbulit data types in python. Difference between set and list is list can contain duplicate value but set don't. 

In [23]:
set1 = {1,2,3,4,5}

In [24]:
#Add an element in the set
set1.add(6)
print(set1)

{1, 2, 3, 4, 5, 6}


In [25]:
#Remove an element from the set
set1.remove(6)
print(set1)

{1, 2, 3, 4, 5}


In [26]:
#Add more than 1 element in the set
ls = [6,7,8]
for i in ls:
    set1.add(i)
print(set1)

{1, 2, 3, 4, 5, 6, 7, 8}


In [27]:
#Extract any element from the set
set1.pop()

1

In [28]:
#2. Write a program to remove the duplicates from the list and a single copy of each element
ls = [1,1,1,2,2,2,3,4,4,5,6,7,8]
set1 = set(ls)
ls1 = list(set1)
print(ls1)

[1, 2, 3, 4, 5, 6, 7, 8]


# Tuple

# What is a tuple?
Tuple is one of the data type in python. Tuple are used to store the multiple element in a single Variable. Tuple are immutable.

In [29]:
tup1 = (1,"hi",34,2.5,45,21)

In [30]:
tup1

(1, 'hi', 34, 2.5, 45, 21)

In [31]:
# Changing "hi" to "hello"
list1 = list(tup1)
list1[1] = "hello"
tup1 = tuple(list1)
print(tup1)

(1, 'hello', 34, 2.5, 45, 21)


In [32]:
#Create a tuple with single element
tup = (1,)
tup

(1,)

In [33]:
#Extracting value from tuple using indexing
tup1[2]

34

In [34]:
#slicing tuple
tup1[1:3]

('hello', 34)

In [35]:
#(d) multiple assignments using tuple

# Dictionary

In [36]:
#Creating empty dictionary
dict1 = {}
print(dict1)
type(dict1)

{}


dict

In [37]:
#adding item to the dictionary
dict1.update({"Fruits" : "Banana"})

In [38]:
dict1

{'Fruits': 'Banana'}

In [39]:
#modifying one value
dict1["Fruits"] = "Apple"

In [40]:
dict1

{'Fruits': 'Apple'}

In [41]:
#2.Write a program to read a string.Count number of occurance of each character in the string using dictionary:

string = "Hello"

occurance = {}

for i in string:
    if i in occurance:
        occurance[i] +=1
    else:
        occurance[i] = 1
        
print(occurance)

{'H': 1, 'e': 1, 'l': 2, 'o': 1}


# Module-2 Basic Programming

In [42]:
# For loops
# 2.Write a python program to find sum of positive elements 
list1 = [8,4,3,-1,4,8,-2,6,2,3,9]
s = 0
for i in list1:
    if i> 0 :
        s = s + i
print(s)    

47


In [31]:
# 1.Write a python program with for loop to get output:( 0 0 0 )( 0 0 1 )( 0 1 0 )( 0 1 1 )( 0 2 0 )( 0 2 1 )( 0 3 0 )( 0 3 1 )( 1 0 0 )( 1 0 1 )( 1 1 0 )( 1 1 1 )( 1 2 0 )( 12 1 )( 1 3 0 )( 1 3 1 )( 2 0 0 )( 2 0 1 )( 2 1 0 )( 2 1 1 )( 2 2 0 )( 2 2 1 )( 2 3 0 )( 2 3 1 )

for i in range(0,3):
    for j in range(0,4):
        for k in range(0,2):
            print(i,j,k)


0 0 0
0 0 1
0 1 0
0 1 1
0 2 0
0 2 1
0 3 0
0 3 1
1 0 0
1 0 1
1 1 0
1 1 1
1 2 0
1 2 1
1 3 0
1 3 1
2 0 0
2 0 1
2 1 0
2 1 1
2 2 0
2 2 1
2 3 0
2 3 1


In [44]:
#While Loops
#Write a python program until the number is guessed and give the output as:
#a. If guessed correctly: ’Congratulations, you guessed it’
#b. If guessed no. is greater:’ No, it is a little lower than that.’
#c. If guessed no. is lower:’ No, it is a little higher than that.’

import random

rd = random.randint(1,9)
guess = 0

while guess != rd:
    guess = input("Enter a guess between 1 to 9")


    guess = int(guess)

    if guess < rd:
        print("No, it is a little higher than that.")
    elif guess > rd:
        print("No, it is a little lower than that")
    else:
        print("Congratulations, you guessed it")
        
input()

Enter a guess between 1 to 91
No, it is a little higher than that.
Enter a guess between 1 to 92
No, it is a little higher than that.
Enter a guess between 1 to 93
No, it is a little higher than that.
Enter a guess between 1 to 94
No, it is a little higher than that.
Enter a guess between 1 to 95
No, it is a little higher than that.
Enter a guess between 1 to 96
No, it is a little higher than that.
Enter a guess between 1 to 97
No, it is a little higher than that.
Enter a guess between 1 to 98
No, it is a little higher than that.
Enter a guess between 1 to 99
Congratulations, you guessed it
9


'9'

In [45]:
#Write a python program using for loop to find if a number is prime or not (Use the concept of Sieve of Eratosthenes)

num = int(input())
flag = False

for i in range(2,num):
    if (num%i) == 0:
        flag = True
        break
    
    
        
if flag:
    print("Number is not a prime number")
else:
    print("Number is a prime number")
    

20
Number is not a prime number


# Conditions

1. Write a program that takes user input in integer and stores it in variable marks and then
categorizes it as:
a. Distinction: when marks &gt;= 75
b. First Class: when marks &gt;=60 and &lt;75
c. Second Class: when marks &gt;=50 and &lt;60
d. Pass: when marks &gt;=40 and &lt;50
e. Fail: when marks&lt;40


In [46]:
marks = int(input())

if marks >= 75:
    print("Distinction")
elif marks >= 60 and marks <75:
    print("First Class")
elif marks >= 50 and marks < 60:
    print("Second Class")
elif marks >= 40 and marks <50:
    print("Pass")
else:
    print("Fail")

34
Fail


2. Take 3 numeric inputs and find the greatest value. Like if var1 is greater than var2 then it checks
if var1 is also greater than var3.

In [47]:
var1 = int(input())
var2 = int(input())
var3 = int(input())

if var1 > var2 and var1 > var3:
    print("var1 is the greatest value")
elif var2> var1 and var2> var3:
    print("var2 is the greatest value")
else:
    print("var3 is the greatest value")
    

34
40
56
var3 is the greatest value


5. Write a python program to find the Area of the triangle also check if the sides entered can create
a triangle or not give the result as “sides entered do not form a triangle” if it is not from the
triangle

In [48]:
a = int(input("Enter First side:"))
b = int(input("Enter Second side:"))
c = int(input("Enter third side:"))

s= (a+b+c)/2
area = (s*(s-a)*(s-b)*(s-c))**0.5

print("Area of traingle =",area)

if a+b>c and a+c>b and b+c>a:
    print("Sides entered form a triangle")
else:
    print("Sides entered do not form a triangle")

Enter First side:2
Enter Second side:3
Enter third side:4
Area of traingle = 2.9047375096555625
Sides entered form a triangle


# Module-3– User Defined Function

1.Write a function is_reverse (string1, string2) to return true if string1 is the reverse of string2:

In [49]:
def is_reserve(string1, string2):
    if string1 == string2[::-1]:
        return True
    else:
        return False
    

In [50]:
is_reserve("stop","pots")

True

In [51]:
is_reserve("stop","stop")

False

2. Write a Python code to check whether the given number is strong. Strong Numbers are numbers
whose sum of the factorial of digits is equal to the original number (Example: 145 = 1! +4! + 5!).

In [52]:
def strong_number(a):
    a_copy = a
    s= 0
    while(a):
        i =1
        fact  = 1
        rem = a%10
        while(i<= rem):
            fact = fact*i
            i = i+1
        s = s+ fact
        a = a//10
    if(s == a_copy):
        print("The number is a strong number")
    else:
        print("The number is not a strong number")
        
            

In [53]:
strong_number(145)

The number is a strong number


In [54]:
strong_number(222)

The number is not a strong number


# Apply Function

1. Write a program to increase the rating by one of the films is a thriller, but only if the IMDB rating
is less than or equal to 10. Also, if the film is a comedy, deduct one point from the ranking. Use
Dataframe: IMDB-Movie-Data

In [2]:
import numpy as np
import pandas as pd

In [56]:
df = pd.read_csv("IMDB-Movie-Data.csv")

In [57]:
df.shape

(1000, 12)

In [58]:
df.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                1000 non-null   int64  
 1   Title               1000 non-null   object 
 2   Genre               1000 non-null   object 
 3   Description         1000 non-null   object 
 4   Director            1000 non-null   object 
 5   Actors              1000 non-null   object 
 6   Year                1000 non-null   int64  
 7   Runtime (Minutes)   1000 non-null   int64  
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64  
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB


In [60]:
def new_rating(genre, rating):
    if "Thriller" in genre and rating <=10:
        return(rating + 1)
    elif "Comedy" in genre:
        return(rating -1)
    else:
        return rating
    

In [61]:
df["New_rating"] = df.apply(lambda x: new_rating(x["Genre"],x["Rating"]), axis = 1)

In [62]:
df

Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1       2               Prometheus  Adventure,Mystery,Sci-Fi   
2       3                    Split           Horror,Thriller   
3       4                     Sing   Animation,Comedy,Family   
4       5            Suicide Squad  Action,Adventure,Fantasy   
..    ...                      ...                       ...   
995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996   997          Hostel: Part II                    Horror   
997   998   Step Up 2: The Streets       Drama,Music,Romance   
998   999             Search Party          Adventure,Comedy   
999  1000               Nine Lives     Comedy,Family,Fantasy   

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley Scott   
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4    A secret government agency recruits some of th...            David Ayer   
..                                                 ...                   ...   
995  A tight-knit team of rising investigators, alo...             Billy Ray   
996  Three American college students studying abroa...              Eli Roth   
997  Romantic sparks occur between two dance studen...            Jon M. Chu   
998  A pair of friends embark on a mission to reuni...        Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012   
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016   
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016   
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
..                                                 ...   ...   
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015   
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007   
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008   
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  \
0                  121     8.1  757074              333.13       76.0   
1                  124     7.0  485820              126.46       65.0   
2                  117     7.3  157606              138.12       62.0   
3                  108     7.2   60545              270.32       59.0   
4                  123     6.2  393727              325.02       40.0   
..                 ...     ...     ...                 ...        ...   
995                111     6.2   27585                 NaN       45.0   
996                 94     5.5   73152               17.54       46.0   
997                 98     6.2   70699               58.01       50.0   
998                 93     5.6    4881                 NaN       22.0   
999                 87     5.3   12435               19.64       11.0   

     New_rating  
0           8.1  
1           7.0  
2           8.3  
3           6.2  
4           6.2  
..          ...  
995         6.2  
996         5.5  
997         6.2  
998         4.6  
999         4.3  

[1000 rows x 13 columns]

2. find rows where the number of words in the movie title is higher than or equal to four.

In [63]:
df["num_word_title"] = df.apply(lambda x: len(x["Title"].split(" ")), axis = 1)

new_df = df[df["num_word_title"]>=4]
new_df.head()

Rank                                    Title                       Genre  \
0      1                  Guardians of the Galaxy     Action,Adventure,Sci-Fi   
8      9                       The Lost City of Z  Action,Adventure,Biography   
10    11  Fantastic Beasts and Where to Find Them    Adventure,Family,Fantasy   
15    16                  The Secret Life of Pets  Animation,Adventure,Comedy   
21    22                    Manchester by the Sea                       Drama   

                                          Description          Director  \
0   A group of intergalactic criminals are forced ...        James Gunn   
8   A true-life drama, centering on British explor...        James Gray   
10  The adventures of writer Newt Scamander in New...       David Yates   
15  The quiet life of a terrier named Max is upend...      Chris Renaud   
21  A depressed uncle is asked to take care of his...  Kenneth Lonergan   

                                               Actors  Year  \
0   Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
8   Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016   
10  Eddie Redmayne, Katherine Waterston, Alison Su...  2016   
15  Louis C.K., Eric Stonestreet, Kevin Hart, Lake...  2016   
21  Casey Affleck, Michelle Williams, Kyle Chandle...  2016   

    Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  \
0                 121     8.1  757074              333.13       76.0   
8                 141     7.1    7188                8.01       78.0   
10                133     7.5  232072              234.02       66.0   
15                 87     6.6  120259              368.31       61.0   
21                137     7.9  134213               47.70       96.0   

    New_rating  num_word_title  
0          8.1               4  
8          7.1               5  
10         7.5               7  
15         5.6               5  
21         7.9               4

# Module 4 Numpy Array

1. Create a numpy array with the number of elements equals your age. The value of array elements
is a random number between 10 to your age

In [64]:
Array = np.arange(24)
Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [65]:
# 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array
Array = np.arange(1,50,3)
print(Array)
print(len(Array))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
17


In [66]:
#3. Create an equally spaced numpy array with 27 elements between 4 and 7¶
Array = np.linspace(4,7, num = 27)
Array

array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

In [67]:
#4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.
Array = np.random.rand(5,4)
Round_off = np.round_(Array, 2)
print(Round_off)

[[0.45 0.03 0.77 0.3 ]
 [0.52 0.39 0.14 0.79]
 [0.37 0.82 0.65 0.09]
 [0.83 0.14 0.92 0.06]
 [0.45 0.35 0.96 0.89]]


In [70]:
#5. Create the one dimensional array of zeros of random length below 20 with the data type int32
Array = np.zeros(20, dtype = np.int32)
Array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
#6. Create a two dimensional array of ones of random row and column lengths with the data type of float32
Array = np.ones([5,4], dtype = np.float32)
Array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [18]:
# 7. Create a matrix exactly as same as shown below and print its shape, type and dtype 
Arr = np.array([9,25,50,34,45,3,34,34,65,2,5,7,3,76,3,7,8,6,54,6,23,12,8,5,8]).reshape([5,5])
Arr

array([[ 9, 25, 50, 34, 45],
       [ 3, 34, 34, 65,  2],
       [ 5,  7,  3, 76,  3],
       [ 7,  8,  6, 54,  6],
       [23, 12,  8,  5,  8]])

In [19]:
Arr.shape

(5, 5)

In [20]:
type(Arr)

numpy.ndarray

In [22]:
Arr.dtype

dtype('int32')

In [27]:
#8. Access the center pixel of the matrix defined in the question no 8 ( Don&#39;t enter the row and column index explicitely)


# Module - 5 Pandas

In [4]:
#1.Create a series with marks of unit test 1 [56,67,42,39,96,84] and then create index of this series as
#["Rahul","ram","sarvan","nisha","swati","raju"]

Unit_test_1 = np.array([56,67,42,39,96,84])

ser = pd.Series(Unit_test_1)
ser

0    56
1    67
2    42
3    39
4    96
5    84
dtype: int32

In [7]:
ser = pd.Series(Unit_test_1, index= ["Rahul","ram","sarvan","nisha","swati","raju"] )
ser

Rahul     56
ram       67
sarvan    42
nisha     39
swati     96
raju      84
dtype: int32

In [9]:
#Create another series with of unit test 2 [53,77,51,32,92,60] for all the same names mentioned above
Unit_test_2 = np.array([53,77,51,32,92,60])

ser2 =  pd.Series(Unit_test_2, index= ["Rahul","ram","sarvan","nisha","swati","raju"] )
ser2

Rahul     53
ram       77
sarvan    51
nisha     32
swati     92
raju      60
dtype: int32

In [10]:
#3.Now find the average marks obtained by each students.

Avg_ser = (ser + ser2)/2
Avg_ser

Rahul     54.5
ram       72.0
sarvan    46.5
nisha     35.5
swati     94.0
raju      72.0
dtype: float64

In [12]:
#4.Create a new series for students "sarvan" and "nisha" with marks 52 and 36.
data = np.array([52,36])
new_ser  = pd.Series(data, index= ["sarvan", "nisha"])

new_ser

sarvan    52
nisha     36
dtype: int32

In [15]:
#5.Replace marks of &#39;sarvan&#39; and &#39;nisha&#39; with marks 52 and 36 in average marks series.
Avg_ser.update(new_ser)
Avg_ser

Rahul     54.5
ram       72.0
sarvan    52.0
nisha     36.0
swati     94.0
raju      72.0
dtype: float64

In [17]:
#6. Find out students who obtained more then 70
above_70 = pd.Series(Avg_ser).where(lambda x: x > 70).dropna()
above_70

ram      72.0
swati    94.0
raju     72.0
dtype: float64